name: Deploy Sales Report to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Tests and Exercices/JavaScript/Grafico Relatorio de Vendas/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up deployment folder
        run: |
          mkdir -p public
          cp -R "Tests and Exercices/JavaScript/Grafico Relatorio de Vendas/." public/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
